# Generated by Django 3.1.1 on 2020-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_drawing_owner'),
    ]

    operations = [
    ]
